/**
 * Popular brands & models in Latvia (CSDD fleet + ss.com used market).
 * Categories: light | suv | van | commercial
 */
export const LV_CATALOG: {
  brand: string;
  models: { name: string; cat: "light" | "suv" | "van" | "commercial" }[];
}[] = [
  {
    brand: "Volkswagen",
    models: [
      { name: "Golf", cat: "light" },
      { name: "Passat", cat: "light" },
      { name: "Polo", cat: "light" },
      { name: "Jetta", cat: "light" },
      { name: "Arteon", cat: "light" },
      { name: "Tiguan", cat: "suv" },
      { name: "T-Roc", cat: "suv" },
      { name: "T-Cross", cat: "suv" },
      { name: "Touareg", cat: "suv" },
      { name: "Touran", cat: "suv" },
      { name: "Sharan", cat: "suv" },
      { name: "Transporter", cat: "van" },
      { name: "Caddy", cat: "van" },
      { name: "Crafter", cat: "commercial" },
    ],
  },
  {
    brand: "Audi",
    models: [
      { name: "A3", cat: "light" },
      { name: "A4", cat: "light" },
      { name: "A5", cat: "light" },
      { name: "A6", cat: "light" },
      { name: "A7", cat: "light" },
      { name: "A8", cat: "light" },
      { name: "Q2", cat: "suv" },
      { name: "Q3", cat: "suv" },
      { name: "Q5", cat: "suv" },
      { name: "Q7", cat: "suv" },
      { name: "Q8", cat: "suv" },
      { name: "e-tron", cat: "suv" },
    ],
  },
  {
    brand: "Volvo",
    models: [
      { name: "S60", cat: "light" },
      { name: "S90", cat: "light" },
      { name: "V40", cat: "light" },
      { name: "V60", cat: "light" },
      { name: "V70", cat: "light" },
      { name: "V90", cat: "light" },
      { name: "XC40", cat: "suv" },
      { name: "XC60", cat: "suv" },
      { name: "XC90", cat: "suv" },
      { name: "C40", cat: "suv" },
    ],
  },
  {
    brand: "BMW",
    models: [
      { name: "1 Series", cat: "light" },
      { name: "2 Series", cat: "light" },
      { name: "3 Series", cat: "light" },
      { name: "4 Series", cat: "light" },
      { name: "5 Series", cat: "light" },
      { name: "7 Series", cat: "light" },
      { name: "X1", cat: "suv" },
      { name: "X2", cat: "suv" },
      { name: "X3", cat: "suv" },
      { name: "X4", cat: "suv" },
      { name: "X5", cat: "suv" },
      { name: "X6", cat: "suv" },
      { name: "X7", cat: "suv" },
    ],
  },
  {
    brand: "Toyota",
    models: [
      { name: "Yaris", cat: "light" },
      { name: "Corolla", cat: "light" },
      { name: "Camry", cat: "light" },
      { name: "Avensis", cat: "light" },
      { name: "Auris", cat: "light" },
      { name: "Prius", cat: "light" },
      { name: "RAV4", cat: "suv" },
      { name: "Yaris Cross", cat: "suv" },
      { name: "C-HR", cat: "suv" },
      { name: "Highlander", cat: "suv" },
      { name: "Land Cruiser", cat: "suv" },
      { name: "Proace", cat: "van" },
      { name: "Hilux", cat: "commercial" },
    ],
  },
  {
    brand: "Mercedes-Benz",
    models: [
      { name: "A-Class", cat: "light" },
      { name: "B-Class", cat: "light" },
      { name: "C-Class", cat: "light" },
      { name: "E-Class", cat: "light" },
      { name: "S-Class", cat: "light" },
      { name: "CLA", cat: "light" },
      { name: "CLS", cat: "light" },
      { name: "GLA", cat: "suv" },
      { name: "GLB", cat: "suv" },
      { name: "GLC", cat: "suv" },
      { name: "GLE", cat: "suv" },
      { name: "GLS", cat: "suv" },
      { name: "G-Class", cat: "suv" },
      { name: "V-Class", cat: "van" },
      { name: "Vito", cat: "van" },
      { name: "Sprinter", cat: "commercial" },
    ],
  },
  {
    brand: "Škoda",
    models: [
      { name: "Fabia", cat: "light" },
      { name: "Scala", cat: "light" },
      { name: "Octavia", cat: "light" },
      { name: "Superb", cat: "light" },
      { name: "Rapid", cat: "light" },
      { name: "Kamiq", cat: "suv" },
      { name: "Karoq", cat: "suv" },
      { name: "Kodiaq", cat: "suv" },
      { name: "Enyaq", cat: "suv" },
    ],
  },
  {
    brand: "Opel",
    models: [
      { name: "Corsa", cat: "light" },
      { name: "Astra", cat: "light" },
      { name: "Insignia", cat: "light" },
      { name: "Mokka", cat: "suv" },
      { name: "Crossland", cat: "suv" },
      { name: "Grandland", cat: "suv" },
      { name: "Zafira", cat: "suv" },
      { name: "Vivaro", cat: "van" },
      { name: "Movano", cat: "commercial" },
    ],
  },
  {
    brand: "Ford",
    models: [
      { name: "Fiesta", cat: "light" },
      { name: "Focus", cat: "light" },
      { name: "Mondeo", cat: "light" },
      { name: "Puma", cat: "suv" },
      { name: "Kuga", cat: "suv" },
      { name: "Explorer", cat: "suv" },
      { name: "S-Max", cat: "suv" },
      { name: "Galaxy", cat: "suv" },
      { name: "Transit", cat: "van" },
      { name: "Transit Custom", cat: "van" },
      { name: "Ranger", cat: "commercial" },
    ],
  },
  {
    brand: "Nissan",
    models: [
      { name: "Micra", cat: "light" },
      { name: "Leaf", cat: "light" },
      { name: "Qashqai", cat: "suv" },
      { name: "Juke", cat: "suv" },
      { name: "X-Trail", cat: "suv" },
      { name: "Pathfinder", cat: "suv" },
      { name: "Navara", cat: "commercial" },
      { name: "NV200", cat: "van" },
    ],
  },
  {
    brand: "Renault",
    models: [
      { name: "Clio", cat: "light" },
      { name: "Megane", cat: "light" },
      { name: "Talisman", cat: "light" },
      { name: "Captur", cat: "suv" },
      { name: "Kadjar", cat: "suv" },
      { name: "Austral", cat: "suv" },
      { name: "Scenic", cat: "suv" },
      { name: "Espace", cat: "suv" },
      { name: "Trafic", cat: "van" },
      { name: "Master", cat: "commercial" },
    ],
  },
  {
    brand: "Hyundai",
    models: [
      { name: "i20", cat: "light" },
      { name: "i30", cat: "light" },
      { name: "Elantra", cat: "light" },
      { name: "Tucson", cat: "suv" },
      { name: "Kona", cat: "suv" },
      { name: "Santa Fe", cat: "suv" },
      { name: "Ioniq 5", cat: "suv" },
      { name: "H-1", cat: "van" },
    ],
  },
  {
    brand: "Kia",
    models: [
      { name: "Rio", cat: "light" },
      { name: "Ceed", cat: "light" },
      { name: "Optima", cat: "light" },
      { name: "Sportage", cat: "suv" },
      { name: "Niro", cat: "suv" },
      { name: "Sorento", cat: "suv" },
      { name: "Stonic", cat: "suv" },
      { name: "EV6", cat: "suv" },
    ],
  },
  {
    brand: "Mazda",
    models: [
      { name: "2", cat: "light" },
      { name: "3", cat: "light" },
      { name: "6", cat: "light" },
      { name: "CX-3", cat: "suv" },
      { name: "CX-5", cat: "suv" },
      { name: "CX-30", cat: "suv" },
      { name: "CX-60", cat: "suv" },
      { name: "MX-5", cat: "light" },
    ],
  },
  {
    brand: "Peugeot",
    models: [
      { name: "208", cat: "light" },
      { name: "308", cat: "light" },
      { name: "508", cat: "light" },
      { name: "2008", cat: "suv" },
      { name: "3008", cat: "suv" },
      { name: "5008", cat: "suv" },
      { name: "Partner", cat: "van" },
      { name: "Expert", cat: "van" },
      { name: "Boxer", cat: "commercial" },
    ],
  },
  {
    brand: "Honda",
    models: [
      { name: "Civic", cat: "light" },
      { name: "Accord", cat: "light" },
      { name: "Jazz", cat: "light" },
      { name: "CR-V", cat: "suv" },
      { name: "HR-V", cat: "suv" },
      { name: "ZR-V", cat: "suv" },
    ],
  },
  {
    brand: "Mitsubishi",
    models: [
      { name: "Lancer", cat: "light" },
      { name: "ASX", cat: "suv" },
      { name: "Outlander", cat: "suv" },
      { name: "Eclipse Cross", cat: "suv" },
      { name: "Pajero", cat: "suv" },
      { name: "L200", cat: "commercial" },
    ],
  },
  {
    brand: "Citroën",
    models: [
      { name: "C3", cat: "light" },
      { name: "C4", cat: "light" },
      { name: "C5", cat: "light" },
      { name: "C3 Aircross", cat: "suv" },
      { name: "C5 Aircross", cat: "suv" },
      { name: "Berlingo", cat: "van" },
      { name: "Jumpy", cat: "van" },
      { name: "Jumper", cat: "commercial" },
    ],
  },
  {
    brand: "SEAT",
    models: [
      { name: "Ibiza", cat: "light" },
      { name: "Leon", cat: "light" },
      { name: "Arona", cat: "suv" },
      { name: "Ateca", cat: "suv" },
      { name: "Tarraco", cat: "suv" },
      { name: "Alhambra", cat: "suv" },
    ],
  },
  {
    brand: "Dacia",
    models: [
      { name: "Sandero", cat: "light" },
      { name: "Logan", cat: "light" },
      { name: "Duster", cat: "suv" },
      { name: "Jogger", cat: "suv" },
      { name: "Spring", cat: "light" },
    ],
  },
  {
    brand: "Tesla",
    models: [
      { name: "Model 3", cat: "light" },
      { name: "Model S", cat: "light" },
      { name: "Model Y", cat: "suv" },
      { name: "Model X", cat: "suv" },
    ],
  },
  {
    brand: "Porsche",
    models: [
      { name: "911", cat: "light" },
      { name: "Panamera", cat: "light" },
      { name: "Cayenne", cat: "suv" },
      { name: "Macan", cat: "suv" },
      { name: "Taycan", cat: "light" },
    ],
  },
  {
    brand: "Lexus",
    models: [
      { name: "IS", cat: "light" },
      { name: "ES", cat: "light" },
      { name: "NX", cat: "suv" },
      { name: "RX", cat: "suv" },
      { name: "UX", cat: "suv" },
    ],
  },
  {
    brand: "Subaru",
    models: [
      { name: "Impreza", cat: "light" },
      { name: "Legacy", cat: "light" },
      { name: "Forester", cat: "suv" },
      { name: "Outback", cat: "suv" },
      { name: "XV", cat: "suv" },
    ],
  },
  {
    brand: "Jeep",
    models: [
      { name: "Renegade", cat: "suv" },
      { name: "Compass", cat: "suv" },
      { name: "Cherokee", cat: "suv" },
      { name: "Grand Cherokee", cat: "suv" },
      { name: "Wrangler", cat: "suv" },
    ],
  },
  {
    brand: "Land Rover",
    models: [
      { name: "Discovery", cat: "suv" },
      { name: "Discovery Sport", cat: "suv" },
      { name: "Range Rover", cat: "suv" },
      { name: "Range Rover Sport", cat: "suv" },
      { name: "Range Rover Evoque", cat: "suv" },
      { name: "Defender", cat: "suv" },
    ],
  },
  {
    brand: "Fiat",
    models: [
      { name: "500", cat: "light" },
      { name: "Panda", cat: "light" },
      { name: "Tipo", cat: "light" },
      { name: "500X", cat: "suv" },
      { name: "Doblo", cat: "van" },
      { name: "Ducato", cat: "commercial" },
    ],
  },
];
